### ISSUE TITLE
Chatroom separate from game window

### ISSUE THREAD

**Issue by XhenryZhang** [ucsb-cs48-s20/project-s1-t4-missile#86]
As a user, when I click on screen in the chat room area, I don't want anything to be affected in the main game since my intention is to chat.

- [x] clicking on the chatroom doesn't register the command to fire a missile in that direction

- [x] typing the numbers 0-9 into the chat doesn't register the command to switch game variables in debug mode

- [x] typing '+' or '-' into the chat doesn't modify game variables in debug mode

**Comment by jsun454** [comment]
Branch: chat-game-separation
